# Generated by Django 4.0.4 on 2022-05-01 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dept_id',
            new_name='department_id',
        ),
    ]
